### ISSUE TITLE
Cannot read some images from the TCGA dataset

### ISSUE THREAD

**Issue by AjeyPaiK** [NKI-AI/dlup#111]
I am trying to use the following code snippet to read an image from the TCGA dataset.
```
import SlideImage from dlup
from dlup.experimental_backends import ImageBackend
from pathlib import Path

image_path = Path(/mnt/archive/data/pathology/TCGA/images/gdc_manifest.2021-11-01_diagnostic_breast.txt/c438e25f-5
8ac-49ec-94a9-00b3b2262d86/TCGA-OL-A5RY-01Z-00-DX1.AE4E9D74-FC1C-4C1E-AE6D-5DF38899BBA6.svs)

with SlideImage.from_file_path(image_path, backend=ImageBackend.OPENSLIDE) as slide_image:
      scaling_factor = slide_image.mpp
      return scaling_factor
```
When I run it, I get the following error:

```Traceback (most recent call last):
  File "/home/a.karkala/.conda/envs/mammaprint/lib/python3.9/site-packages/dlup/experimental_backends/openslide.py", line 41, in __init__
    mpp_x = float(self.properties[openslide.PROPERTY_NAME_MPP_X])
  File "/home/a.karkala/.conda/envs/mammaprint/lib/python3.9/site-packages/openslide/__init__.py", line 278, in __getitem__
    raise KeyError()
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a.karkala/.conda/envs/mammaprint/lib/python3.9/site-packages/dlup/_image.py", line 124, in from_file_path
    wsi = backend(wsi_file_path)
  File "/home/a.karkala/.conda/envs/mammaprint/lib/python3.9/site-packages/dlup/experimental_backends/__init__.py", line 135, in __call__
    return self.value(*args)
  File "/home/a.karkala/.conda/envs/mammaprint/lib/python3.9/site-packages/dlup/experimental_backends/openslide.py", line 45, in __init__
    raise UnsupportedSlideError(f"slide property mpp is not available.", str(filename))
dlup._exceptions.UnsupportedSlideError: (UnsupportedSlideError(...), "slide '/mnt/archive/data/pathology/TCGA/images/gdc_manifest.2021-11-01_diagnostic_breast.txt/c438e25f-58ac-49ec-94
a9-00b3b2262d86/TCGA-OL-A5RY-01Z-00-DX1.AE4E9D74-FC1C-4C1E-AE6D-5DF38899BBA6.svs': slide property mpp is not available.")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a.karkala/.conda/envs/mammaprint/lib/python3.9/site-packages/dlup/_image.py", line 126, in from_file_path
    raise UnsupportedSlideError(f"Unsupported file: {wsi_file_path}")
dlup._exceptions.UnsupportedSlideError: (UnsupportedSlideError(...), 'Unsupported file: /mnt/archive/data/pathology/TCGA/images/gdc_manifest.2021-11-01_diagnostic_breast.txt/c438e25f-5
8ac-49ec-94a9-00b3b2262d86/TCGA-OL-A5RY-01Z-00-DX1.AE4E9D74-FC1C-4C1E-AE6D-5DF38899BBA6.svs')
```

dlup version: 0.3.5

**Comment by AjeyPaiK** [comment]
Apparently, this particular image file doesn't have an mpp property and hence dlup breaks (as expected). Closing the issue.
