### ISSUE TITLE
`SlideImage.read_region` fails because the box overflows the region in `PIL.Image.resize`

### ISSUE THREAD

**Issue by YoniSchirris** [NKI-AI/dlup#126]
**Describe the bug**
`SlideImage.read_region` fails because the box overflows the region in `PIL.Image.resize`

**To Reproduce**
A clear and concise description on how to reproduce the problem.

```
Python 3.9.12 (main, Aug 18 2022, 18:05:59)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlup
>>> from dlup.data.dataset import TiledROIsSlideImageDataset
>>> dlup.__version__
'0.3.12'
>>> slide = ''  # See internal slack
>>> mpp = 8.
>>> tile_size = 256
>>> tile_overlap = 0
>>> dataset = TiledROIsSlideImageDataset.from_standard_tiling(
                slide, mpp, (tile_size, tile_size), (tile_overlap, tile_overlap)
            )
>>> [region for region in dataset]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "/home/y.schirris/stils_pipeline_yoni/.env/lib/python3.9/site-packages/dlup/data/dataset.py", line 266, in __iter__
    yield self[i]
  File "/home/y.schirris/stils_pipeline_yoni/.env/lib/python3.9/site-packages/dlup/data/dataset.py", line 430, in __getitem__
    data = super().__getitem__(index)
  File "/home/y.schirris/stils_pipeline_yoni/.env/lib/python3.9/site-packages/dlup/data/dataset.py", line 237, in __getitem__
    region = region_view.read_region(coordinates, region_size)
  File "/home/y.schirris/stils_pipeline_yoni/.env/lib/python3.9/site-packages/dlup/_region.py", line 59, in read_region
    region = self._read_region_impl(location + offset, clipped_region_size)
  File "/home/y.schirris/stils_pipeline_yoni/.env/lib/python3.9/site-packages/dlup/_image.py", line 56, in _read_region_impl
    return self._wsi.read_region((x, y), self._scaling, (w, h))
  File "/home/y.schirris/stils_pipeline_yoni/.env/lib/python3.9/site-packages/dlup/_image.py", line 229, in read_region
    return region.resize(size, resample=PIL.Image.Resampling.LANCZOS, box=box)
  File "/home/y.schirris/stils_pipeline_yoni/.env/lib/python3.9/site-packages/PIL/Image.py", line 2093, in resize
    im = im.resize(size, resample, box)
  File "/home/y.schirris/stils_pipeline_yoni/.env/lib/python3.9/site-packages/PIL/Image.py", line 2115, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: box can't exceed original image size
```

**Expected behavior**
I expect to be able to loop over all the regions in the slide without issues.

**Environment**
dlup version: 3.9.12
How installed: pip
Python version: 3.9.12
Operating System: ubuntu

**Additional context**
`dlup._image`:l217-219 states
```
        # By casting to int we introduce a small error in the right boundary leading
        # to a smaller region which might lead to the target region to overflow from the sampled
        # region.
```
Which is likely what is happening here. 

When debugging at l229, the values were as follows:

```
>>> box
(4.559346650118641, 4.833926203467854, 268.37799153845594, 223.30874150162217)
>>> region.size
(273, 223)
```

or, with more details (note that many variables are overwritten. the value next to each variable is the final value of the variable as the value updates when it is overwritten)
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/35081060/204281272-8481da08-82c7-4d7b-8541-fd26afce3808.png">

**Comment by YoniSchirris** [comment]
After testing further, this happens for every `.mrxs` file that I have in my dataset.

**Comment by YoniSchirris** [comment]
Having tested several mpps and tile sizes, this happens essentially every time, and can happen either in row or column direction

**Comment by jonasteuwen** [comment]
Fixed in main
